[package]
name = "kaleidoscope-rust-repl"
version = "0.1.0"
authors = ["Chen Junda <ddadaal@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kaleidoscope-rust-core = { path = "../core" }